### PR TITLE
Fix #101: Fix styleguide warnings

### LINKED ISSUE #101: React warnings on styleguide
Hello,

There are too many React warnings thrown at styleguide start:

- "Warning: `value` prop on `select` should not be null"
- `Select` component is switching between controlled and uncontrolled mode which is not advised by React
- "Warning: Failed prop type: Invalid prop `variance` of value `normal` supplied to `Button`, expected one of ["primary","neutral","light","dark"]."
- "Warning: Failed prop type: Invalid prop `variance` of value `neutral` supplied to `InputFile`, expected one of ["primary","secondary","normal"]"
- `TableFacade`should render children with keys

Please fix those warnings in the stories of these components to limit the noise in the console.

### PR DESCRIPTION
**Pull request by alexandre-lelain**
- Fixed warnings on styleguide
- Fixed as prop of Badge
- Fixed values of textarea & select

[issue #101](https://github.com/attineos/atti-components/issues/101)

### CODE REVIEW

File: src/components/Table/index.js [hunk 1]
```diff
@@ -163,7 +163,7 @@ const Table = ({
 
       <tbody>
         {map(elements, (element, index) => (
-          <React.Fragment>
+          <React.Fragment key={`cell-${index}`}>
```
Comment (VictorGosse) [inline src/components/Table/index.js]: I'm not sure we should rely on this `index`

Comment (VictorGosse) [reply src/components/Table/index.js]: cf https://www.atrakeur.com/blog/web/les-travers-des-react-keys/ ^_^

Comment (alexandre-lelain) [reply src/components/Table/index.js]: Since I prefixed the key with `cell`, there will never be twice the same key. Plus this is what is already being done above in the code, and by yourself if git history is correct ;)

Comment (VictorGosse) [reply src/components/Table/index.js]: The problem is not about having it twice :) The problem is that if we remove the first element, the index of all the other elements will change and so they'll be rerendered :(.
And I'm not always right ^_^

Comment (alexandre-lelain) [reply src/components/Table/index.js]: ooooh indeed good point. I'll change this :)

Comment (alexandre-lelain) [reply src/components/Table/index.js]: Fixed in both cases

Comment (VictorGosse) [reply src/components/Table/index.js]: You da best ! approved
